
{
    'name': 'Hiworth Construction Management',
    'version': '1.0',
    'category': 'Project',
    'sequence': 21,
    'description': """ Project Cost Estimation """,
    'depends': ['sale','project','mrp','purchase','document','hr','hiworth_accounting'],
    'data': [
         'security/user_groups.xml',
         'security/ir.model.access.csv',
         'security/hide_sale_manufacturing.xml',
         'views/work_order_sequence.xml',
         'views/contractor_bill_sequence.xml',
         'report/alter_default_header_footer.xml',
         'report/project.xml',
         'report/task.xml',
         'report/material_request.xml',
         'report/location_wise_report.xml',
         'report/stock_report.xml',
         'report/common_report_alteration.xml',
         'report/project_report.xml',
         'views/invoice_action_data.xml',
         'views/construction_project_details_view.xml',
         'views/counstruction_menu_view.xml',
         'views/purchase_order_action_data.xml',
         'views/default_project_stages.xml',
         'views/activity_view.xml',
         'views/hiworth_invoice.xml',
         'views/hiworth_accounting_view.xml',
         'views/work_order.xml',
         'views/admin_saction_records.xml',
         'report/product_to_location_report.xml',
         'report/stock_move_report.xml',
         'wizard/stock_transfer_details.xml',
         'views/daily_progress_report.xml',
         'views/work_shedule.xml',
         'views/employee_activity.xml',
         'views/delay_report.xml',
         'views/progress_report.xml',

         'report/activity_reports.xml',
         'data/defaultdata.xml',
         'views/account_payment_schedule.xml',
         'report/contractor_invoices_report.xml',
         'report/task_report_wizarad.xml',
         'views/material_request.xml',
         'views/project_stages.xml'


 #        'project_task_view.xml'
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
}
